In [1]:
import torch

data_path = "../data/filtered_train_test_split/"

POSITIONS = 18

X_train_tensor, y_train_tensor, X_test_tensor, y_test_tensor = {}, {}, {}, {}


for i in range(POSITIONS):
    X_train_tensor[i] = torch.load(data_path + f"X_train_{i}.pt")
    y_train_tensor[i] = torch.load(data_path + f"y_train_{i}.pt")
    X_test_tensor[i] = torch.load(data_path + f"X_test_{i}.pt")
    y_test_tensor[i] = torch.load(data_path + f"y_test_{i}.pt")

print(X_train_tensor[0][:5])
print(y_train_tensor[0][:5])
print(X_test_tensor[0][:5])
print(y_test_tensor[0][:5])

C:\Users\gurgel\AppData\Local\Temp\ipykernel_9516\3230149071.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  X_train_tensor[i] = torch.load(data_path + f"X_train_{i}.pt

tensor([[ 4.4000e+01,  3.8642e-01,  2.9976e-01,  2.1417e-01,  1.3460e-01,
          4.1206e-02, -5.1461e-02, -1.7905e-01, -2.1703e-01, -2.0291e-01,
         -1.9350e-01, -1.5718e-01, -3.3163e-02,  5.2003e-01,  7.1807e-01,
          1.1197e+00,  1.3429e+00,  1.5217e+00,  1.7501e+00,  1.8880e+00,
          2.1980e+00,  1.9848e+00,  1.8394e+00,  1.4780e+00,  1.4555e+00,
          1.1440e+00,  9.0688e-01,  7.6223e-01,  4.3167e-01,  2.0761e-01,
          1.8334e-02, -4.3698e-01, -5.8092e-01, -7.2828e-01, -1.0801e+00,
         -1.2079e+00, -1.2878e+00, -1.4551e+00, -1.5468e+00, -5.2357e-01,
         -5.6683e-01],
        [ 2.6000e+01, -6.9760e-01, -6.8235e-01, -6.4446e-01, -6.4049e-01,
         -6.1060e-01, -5.8075e-01, -5.2102e-01, -4.8339e-01, -4.4630e-01,
         -4.3467e-01, -4.0381e-01, -3.5520e-01, -2.0836e-01, -1.3067e-01,
          5.8470e-02,  2.0659e-01,  2.9838e-01,  4.7208e-01,  6.6080e-01,
          8.7452e-01,  1.0226e+00,  1.0570e+00,  1.0350e+00,  1.0508e+00,
          1.013

In [2]:
from torch.utils.data import DataLoader, TensorDataset

batch_size = 512
num_workers = 16
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

inputs, train_dataset, test_dataset, train_loader, test_loader = {}, {}, {}, {}, {}

for i in range(POSITIONS):
    inputs[i] = X_train_tensor[i].shape[1]

    train_dataset[i] = TensorDataset(X_train_tensor[i], y_train_tensor[i])
    test_dataset[i] = TensorDataset(X_test_tensor[i], y_test_tensor[i])

    train_loader[i] = DataLoader(
        dataset=train_dataset[i],
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True,
    )
    test_loader[i] = DataLoader(
        dataset=test_dataset[i],
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
    )

print(train_loader[0].dataset.tensors)
print(test_loader[0].dataset.tensors)

(tensor([[ 4.4000e+01,  3.8642e-01,  2.9976e-01,  ..., -1.5468e+00,
         -5.2357e-01, -5.6683e-01],
        [ 2.6000e+01, -6.9760e-01, -6.8235e-01,  ...,  3.9905e-01,
          8.6546e-01,  8.5090e-01],
        [ 5.2000e+01, -6.3395e-01, -6.4926e-01,  ...,  4.0282e-01,
         -1.1731e+00, -1.1522e+00],
        ...,
        [ 4.0000e+00,  1.2202e+00,  1.2272e+00,  ...,  1.4772e+00,
          1.6093e+00,  1.5470e+00],
        [ 1.9000e+01, -1.7210e+00, -1.6329e+00,  ...,  1.5486e+00,
          1.6795e+00,  1.7027e+00],
        [ 4.0000e+00, -3.7073e-01, -3.5631e-01,  ..., -1.9827e-02,
          5.4358e-01,  5.1449e-01]]), tensor([0, 0, 0,  ..., 0, 0, 0]))
(tensor([[46.0000, -0.2138, -0.2730,  ..., -0.5477, -1.1744, -1.1432],
        [10.0000, -1.2046, -1.1377,  ...,  0.5050, -1.1571, -1.1429],
        [33.0000, -1.7444, -1.7738,  ...,  0.8641,  1.2261,  1.2260],
        ...,
        [35.0000,  1.3852,  1.5208,  ...,  1.7421, -1.1643, -1.1480],
        [56.0000, -0.8822, -0.9156,  .

In [3]:
import os

from mlp import CsiNeuralNet

save_path = "mlp/"
num_epochs = 1000

for i in range(POSITIONS - 1, -1, -1):
    save_file = f"{save_path}filtered_model_{i}.pth"
    state_file = save_file if os.path.exists(save_file) else None
    net = CsiNeuralNet(inputs[i], device, state_file=state_file, output_dim=2)

    print(f"Training model for position {i}")
    result_model = net.train_model(
        train_loader[i], test_loader[i], save_file, num_epochs
    )
    print(f"Model for position {i} finished training")

c:\Users\gurgel\Desktop\Personal\Projects\UFF\Mestrado\Telecom\HAR\csi\models\mlp.py:53: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(state_

Training model for position 17
Training on device: cuda
Epoch 1/1000, Accuracy: 96.24%, Loss: 0.10329064, In 25.44s
Model saved for epoch 1 with accuracy 95.81%
Epoch 10/1000, Accuracy: 96.39%, Loss: 0.09882917, In 232.48s
Epoch 20/1000, Accuracy: 96.30%, Loss: 0.10150218, In 281.25s
Model saved for epoch 27 with accuracy 95.82%
Epoch 30/1000, Accuracy: 96.58%, Loss: 0.09262733, In 281.24s
Epoch 40/1000, Accuracy: 96.60%, Loss: 0.09164146, In 274.20s
Model saved for epoch 45 with accuracy 95.84%
Epoch 50/1000, Accuracy: 96.77%, Loss: 0.08727520, In 267.53s
Model saved for epoch 55 with accuracy 95.87%
Epoch 60/1000, Accuracy: 96.83%, Loss: 0.08495699, In 268.93s
Epoch 70/1000, Accuracy: 96.76%, Loss: 0.08722974, In 291.48s
Model saved for epoch 74 with accuracy 95.88%
Epoch 80/1000, Accuracy: 96.95%, Loss: 0.08163453, In 294.32s
Epoch 90/1000, Accuracy: 96.72%, Loss: 0.08855072, In 283.27s
Epoch 100/1000, Accuracy: 97.09%, Loss: 0.07799633, In 283.48s
Early stopping at epoch 105 due to